name: Build and deploy slides

on:
  push:
    branches:
      - main

jobs:
  build-slides:
    runs-on: ubuntu-latest
    name: Build slides

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true
          generate-run-shell: true

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install ipykernel
        run: |
          which python
          python -m ipykernel install --user --name oss-culture-scipy2024
          quarto check jupyter

      - name: Render Quarto Project
        run: |
          quarto render index.qmd --output-dir ./_site

      - name: Deploy slides
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GHPAGES_TOKEN }}
          publish_dir: ./_site/
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          enable_jekyll: false
          disable_nojekyll: false
